name: action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up PostgreSQL
        env:
          POSTGRES_USER: hehe
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        run:
          sudo apt-get update
          sudo apt-get install -y postgresql-14 postgresql-contrib
          sudo systemctl start postgresql
          sudo -u postgres psql -c "CREATE DATABASE $POSTGRES_DB;"
          sudo -u postgres psql -c "CREATE USER $POSTGRES_USER WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';"

      - name: Use PostgreSQL database
        run: |
          sudo -u postgres psql -d $POSTGRES_DB -c "SELECT * FROM pg_extension;"

