name: action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up PostgreSQL
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-14 postgresql-contrib
          sudo systemctl start postgresql
          sudo systemctl status postgresql
          sudo -u postgres psql -c "CREATE DATABASE $POSTGRES_DB;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;"
          sudo -u postgres psql -d $POSTGRES_DB -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"
          sudo -u postgres psql -d $POSTGRES_DB -c "SELECT * FROM pg_extension;"

      - name: view postgres.conf
        run: |
          cat /etc/postgresql/14/main/postgresql.conf

      # - name: setup pg_cron
      #   run: |
      #     wget https://github.com/citusdata/pg_cron/archive/refs/tags/v1.5.1.tar.gz
      #     tar -xzf v1.5.1.tar.gz
      #     cd v1.5.1.tar.gz
      #     make install

      # - name: setup pg_partman
      #   run: |
      #     sudo apt-get install postgres-14-partman


      # - name: call DATABASE
      #   run: |
      #     sudo -u postgres psql -d $POSTGRES_DB -c "SELECT * FROM pg_extension;"
      #   env:
      #     POSTGRES_USER: postgres
      #     POSTGRES_PASSWORD: postgres
      #     POSTGRES_DB: testdb

