name: action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: postgres setup
        run : |
          sudo apt -y install postgresql-14
          sudo apt-get -y install postgresql-14-cron
          sudo apt -y install postgresql-14-partman
          sudo apt-get install --yes postgresql-client


      - name: print
        run: |
          psql postgres

      # - name: setup postgres.conf
      #   run: |
      #     echo -e '\nshared_preload_libraries = 'pg_partman_bgw' >> /var/lib/postgresql/data/postgresql.conf
      #     echo -e '\npg_partman_bgw.dbname = 'testdb' >> /var/lib/postgresql/data/postgresql.conf
      #     sudo systemctl restart postgresql.service

