name: action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up PostgreSQL
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-14 postgresql-contrib
          sudo systemctl start postgresql
          sudo systemctl status postgresql
          sudo -u postgres psql -c "CREATE DATABASE $POSTGRES_DB;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;"
          sudo -u postgres psql -d $POSTGRES_DB -c "SELECT * FROM pg_extension;"

      - name: setup pg_cron
        run: |
          sudo apt-get -y install postgresql-14-cron
          echo -e "\nshared_preload_libraries = 'pg_cron'" >> /etc/postgresql/14/main/postgresql.conf
          sudo systemctl restart postgresql
          sudo -u postgres psql -d $POSTGRES_DB -c "CREATE EXTENSION pg_cron;"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb

      - name: setup pg_partman
        run: |
          sudo apt-get install postgres-14-partman
          echo -e "\npg_partman_bgw.dbname = 'testdb'" >> /etc/postgresql/14/main/postgresql.conf
          echo -e "\nshared_preload_libraries = 'pg_partman_bgw'" >> /etc/postgresql/14/main/postgresql.conf
          sudo systemctl restart postgresql
          sudo -u postgres psql -d $POSTGRES_DB -c "CREATE SCHEMA partman;"
          sudo -u postgres psql -d $POSTGRES_DB -c "CREATE EXTENSION pg_partman SCHEMA partman;"

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb

      - name: check extension installation
        run: |
          sudo -u postgres psql -d $POSTGRES_DB -c "SELECT * FROM pg_extension;"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb

