name: action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: go_mysql_suite_test
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: postgres setup
        run : |
          sudo apt -y install postgresql-14

      - name: setup pgcron
        run: |
          sudo apt-get -y install postgresql-14-cron

      - name: setup pgpartman
        run: |
          sudo apt -y install postgresql-14-partman

      - name: setup postgres.conf
        run: |
          psql --help
